# Generated by Django 4.1.1 on 2022-09-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribuidores',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
