# Generated by Django 4.1.1 on 2022-09-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_rename_dirección_distribuidores_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='mail',
            new_name='email',
        ),
    ]
